### ISSUE TITLE
Extension of the properties of a Location to support Libraries Taskforce open data ambitions

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#87] opened 2018-06-13 22:19 UTC
Outstanding issues not dealt with in updates in issue #79 

Additional core properties of a Location, when the location type is '01' (Library / institution) or '02' (Site within library / institution):

  -  current statutory status of library : This is not currently expressible in LCF, and I think that, if we add it, it should be a property of an Authority / institution, not a property of a Location, and so should be added to E14.
  -  library type : This also is not currently expressible in LCF, and I think should also be a property of an Authority / institution, not of a Location.

 - Opening and closing times: I am presuming that these should be associated with a Location rather than with an Authority / institution, since it is the Location that will be open or closed at a particular time. The structure proposed by Solus seems reasonable to me and could be added to the Location entity (E04). The list of opening and closing time overrides will clearly need active periodic maintenance, because dates will vary from year to year. Might there be a case for being able to express seasonal variation, e.g. summer opening times and winter opening times? This could be achieved by adding an optional 'Season' property to the weekly opening times composite.

**Comment by franciscave** [comment] 2018-11-16 13:13
**Statutory Status**

I am waiting for confirmation from members of the Library Taskforce regarding a controlled vocabulary for Statutory Status. My understanding is that there are just two options: Statutory and Non-Statutory; but this needs to be confirmed.

**Library type**

I propose that a new optional element E14D08 Library Type be added to E14 Library Authority/Institution. The element would use a new code list ATY Library Authority/Institution Type, with the following code values as defined by the Libraries Taskforce:

  -  LAL (Local Authority-run Library - staffed)
  -  LAL (Local Authority-run Library - unstaffed)
  -  CL (Commissioned Library)
  -  CRL (Community-run Library, part of Statutory service - volunteer staff)
  -  CRL+ (Community-run Library, part of Statutory service - paid staff)
  -  ICL (Independent Community Library, non-Statutory - volunteer staff)
  -  ICL+ (Independent Community Library, non-Statutory - paid staff)

**Opening and closing times** 

Detailed proposals to follow.

**Comment by franciscave** [comment] 2019-02-28 17:50
I have had confirmation from the DCMS that there are only two Statutory Status options for libraries: Statutory or Non-Statutory. So I believe those are the only code values that need to be added to a new Statutory Status code list (STA).

**Comment by franciscave** [comment] 2019-04-25 12:38
Following the receipt of further clarification from DCMS, I propose two code lists:

### LST Library statutory status

  *Code ID*      |*Code value*       |*Definition*                                                         |*Notes*
  -------------- | ----------------- |-------------------------------------------------------------------  |----------------------------------
  LST01          | 01               | Statutory provision                                              |
  LST02          | 02               | Non-statutory provision                                      |

### LTY Library type

  *Code ID*      |*Code value*       |*Definition*                                                         |*Notes*
  -------------- | ----------------- |-------------------------------------------------------------------  |----------------------------------
  LTY01          | LAL              | Local authority run (funded, run and managed by local authority staff but may be augmented by volunteers)                                                                 |
  LTY02          | LAL-            | Local authority run (funded and managed by the local authority but unstaffed)                                                                                                        |
  LTY03          | CL               | Commissioned library (commissioned and funded by a local authority but delivered by a contracted third party)                                                            |
  LTY04          | CRL             | Community run libraries (some ongoing support, eg funding, stock, guidance from the local authority)                                                                 |
  LTY05          | CRL             | Community run libraries (paid staff may be involved in the day to day running of the library)                                                                                     |
  LTY06          | ICL              | Independent community library (outside the local authority, staffed only by volunteers)                                                                                                      |
  LTY07          | ICL+           | Independent community library (outside the local authority with paid staff) |

While in theory these two lists can be used in any combination, in practice according to DCMS only one public library currently combines type ICL with status 01, and no public libraries currently combine type ICL+ with status 01.

**Comment by franciscave** [comment] 2019-04-25 12:53
I suggest the following modification to the LCF Data Framework, entity E14:

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*   | *Description*                  |
|------------|----------------------------|------------|---------|------------|--------------------------------|
|                 | ...                                      |                  |             |                 |                                               |
| **E14D03** | **Authority / institution name** |     | **1**    | **String** | **The name of this authority/institution**                                                                                        |
| E14D08    | Library statutory status   |                  | 0-1      | Code        | LCF code list **LST**              |
| E14D09    | Library type                     |                  | 0-1      | Code        | LCF code list **LTY**              |
|                 | ...                                      |                  |             |                 |                                               |

Proposed changes to the LCF entity XML binding to follow.

**Comment by franciscave** [comment] 2019-05-03 16:48
I suggest the following modification to the LCF entity XML binding for entity E14:

|       | *Element ID* | *XML structure*             | *Card.* | *Data type* | *Notes* |
|-------|--------------|--------------------------|---------|-------------|---------|
|          |    ...              |                                       |            |                   |              |
| **7** | **E14D03**   | **name**                    | 1          | string         |              |
|    8    |    E14D08    | library-status                 | 0-1     | Code          | LST        |
|    9    |    E14D09    | library-type                   | 0-1      | Code          | LTY        |
|   10   | E14C04       | associated-location         | 0-n     |                  |               |
|          |    ...              |                                       |            |                   |              |

**Comment by franciscave** [comment] 2019-05-28 18:03
Here is a proposal to add opening and closing times to E14.

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*   | *Description*                  |
|------------|----------------------------|------------|---------|------------|--------------------------------|
| **E14D01** | **Authority/institution identifier** |  | **1**[4](#Notes)                                                    | **String** | **The LCF entity identifier used when referring to this authority/institution.**.               |
|     ...        |                                  |                 |             |                   |                                                       |
| E14D08     | Library statutory status   |           | 0-1      | Code        | LCF code list **[LST](LCF-CodeLists.md#LST)**<br/>*Added in v1.2.0*         |
| E14D09     | Library type               |           | 0-1      | Code        | LCF code list **[LTY](LCF-CodeLists.md#LTY)**<br/>*Added in v1.2.0*         |
| *E14C04*   | *Associated location*      |           | 0-n      |            | A location associated with this authority/institution.                                                                                         |
| E14D04.1   | Location association type  |           | 1        | Code       | LCF code list **[LAT](LCF-CodeLists.md#LAT)**          |
| E14D04.2   | Location reference         |           | 1        | String     |                                |
| *E14C04.3*   | Library opening/closing times    |           | 0-n     |               | Only to be used for location association types LAT04 or LAT05  |
| E14D04.3.1   | Day(s) of the week         |            | 0-n     | Code     | LCF code list WKD   |
| *E14C04.3.2* | Season                           |            | 0-n     |        |                                    |
| E14D04.3.2.1 | Season name                |            | 1        | String     |                                 |
| E14D04.3.2.2 | Season start date inclusive  |     | 1        | Date       |                                 |
| E14D04.32.3 | Season end date inclusive   |     | 1        | Date       |                                 |
| E14D04.3.3   | Library opening time     |            | 1        | Time      |                                 |
| E14D04.3.4   | Library closing time       |            | 1        | Time      |                                 |
| E15D04.3.5   | Staffed / un-staffed       |            | 0-1     | Code     | LCF code list STA     |
|     ...        |                                  |                 |             |                   |                                                       |

For code lists WKD and STA I would propose the following:

### WKD Days of the week

  *Code ID*      |*Code value*      |*Definition*   |*Notes*
  -------------- |----------------- |-------------- |----------------------------------
  WKD01         |00                |Unspecified   | Default
  WKD02         |01                |Monday    |
  WKD03         |02                |Tuesday    |
  WKD04         |03                |Wednesday    |
  WKD05         |04                |Thursday    |
  WKD06         |05                |Friday    |
  WKD07         |06                |Saturday    |
  WKD08         |07                |Sunday    |
  WKD09         |11                |Weekdays (Monday to Friday inclusive)    |
  WKD10         |12                |Weekends (Saturday and Sunday) |

### STA Staffed / un-staffed

  *Code ID*      |*Code value*      |*Definition*   |*Notes*
  -------------- |----------------- |-------------- |----------------------------------
  STA01            |00                |Unspecified   | Default
  STA02            |01                |Staffed          | 
  STA03            |02                |Un-staffed    | 
  STA04            |03                |Staffed with voluntary staff | 

I propose that, if repetitions of E14C04.3 overlap in their season/days scope, repetitions with narrower scope override those with wider scope. Non-overlapping repetitions are additive.

I have considered including a code list for seasons - e.g. 'Summer', 'Winter', 'All-year-round' - but it strikes me that specifying date ranges would still be useful, and giving libraries the ability to name their own seasons is more flexible.

I have also considered whether the new structure would better be a property of a Location rather than of an Authority/institution. My feeling is that adding the same structure to the Location entity would also work, but somewhat overloads the Location entity with properties that are perhaps more strongly associated with the particular Authority/institution. An argument in favour of having this structure on the Location entity would be to be able to differentiate opening/closing times for different buildings on the same library site (location type LOT02 versus LOT01). **I'd very much appreciate receiving comments on this point.**

**Comment by franciscave** [comment] 2019-06-03 20:37
A clarification of the interpretation of seasons with overlapping scope. 

If the scope of one season is wholly contained within another season, the season with narrower scope overrides the season with wider scope. This would make it simpler to say specify summer opening/closing times from, say, May to September inclusive, but specify different opening/closing times for August.

If the scope of two seasons overlaps, but neither season wholly contains the other, I think this should be treated as an error, since it cannot be safely determined which season overrides the other.

**Comment by mdovey** [comment] 2019-08-14 15:06
On today's Technical Panel we discussed that "season" wasn't the right terminology, as it was really a service-period (not discussed but given this change it might not be desirable for "name" or "service-period-name" to be mandatory element).

It was also discussed that it would be useful to be able to specify explicitly closed periods as well as explicitly open periods.

**Comment by franciscave** [comment] 2019-08-20 15:39
Following the last Technical Panel discussion of this issue, here is a proposed new structure to replace the previous proposal for library opening/closing times. I propose to change the meaning of code value '00' in list WKD from 'Unspecified' to 'All', since I believe it to be meaningless to specify that a library location is open or closed without being clear about the days of the week to which this applies, and 'All' makes sense when the location service period is a specific date or a period of only a few days. I also feel that a space-separated list of code values is (a) less verbose than having to make the element repeatable and (b) can be validated more readily using regular expressions.

| *Id*          | *Element*                         | *SIP2 ID*  | *Card.* | *Format* | *Description*      |
|------------|----------------------------|------------|---------|------------|-------------------|
| *E14C04.3* | Library location service period |        | 0-n      |            | Only to be used for location association types LAT04 or LAT05<br/>See Notes 1-3 below on interpretation of repetitions of this composite element<br/>*Added in v1.2.0*    |
| E14D04.3.1 | Period name                             |        | 0-1      | String  |                                 |
| E14D04.3.2 | Period start date inclusive        |        | 1         | Date     |                                 |
| E14D04.3.3 | Period end date inclusive         |        | 1         | Date     |                                 |
| E14D04.3.4 | Days of the week                      |        | 0-1      | String  | See Note 5 below.   |
| E14D04.3.4 | Library closed                           |        | 0-1      |             | Explicit statement that the library is closed. Either E14D04.3.4 or one or more of E14C04.3.5 must be specified in each instance of E14C04.3. |
|*E14C04.3.5*| Library open                            |        | 0-n      |             | See Note 4 below on interpretation of repetitions of this composite element. |
|E15D04.3.5.1| Opening time                          |        | 1         | Time     |                                  |
|E15D04.3.5.2| Closing time                            |        | 1         | Time     |                                  |
|E15D04.3.5.3| Staffed / un-staffed                 |        | 0-1      | Code    | LCF code list **[STA](LCF-CodeLists.md#STA)**     |

**Notes on interpretation of repeated instances of E14C04.3 Library opening/closing times**

1. If the period start/end dates of instances of E14C04.3 do not overlap, i.e. they are mutually exclusive, all are applicable.

2. If the date period of one instance of E14C04.3 is wholly contained within the date period of another instance, the instance with the wider scope is overridden by the instance with the narrow scope to the extent of the scope of the latter. An example would be to specify opening and closing times for an academic term in one instance and different times for a specific week of that term in a second instance.

3. If the date periods of two instances of E14C04.3 overlap, but the date period of one instance is not wholly contained within the date period of another instance, the instances cannot be interpreted unambiguously and the terminal application should ignore these instances of E14C04.3 and any other instances of E14C04.3 that are wholly or partially contained within them.

4. If the time periods of two or more instances of E14C04.3.5 overlap, the repeated instances cannot be interpreted unambiguously and the terminal application should ignore these instances of E14C04.3.5.

5. Days of the week are specified by a space-separated list of code values taken from LCF code list **[WKD](LCF-CodeLists.md#WKD)**.

**Comment by franciscave** [comment] 2019-08-21 10:09
In the following I've made the structure more balanced, and I've corrected some typos. With this structure it is possible to specify on which days of the week the library is closed all day within a given service period and on which days of the week the library is open at least once in the day. The composite E14C04.3.4 could be eliminated by adding a code value meaning 'None' to WKD, but I think that the proposed structure is more clear.

| *Id*          | *Element*                         | *SIP2 ID*  | *Card.* | *Format* | *Description*      |
|------------|----------------------------|------------|---------|------------|-------------------|
| *E14C04.3* | Library location service period |        | 0-n      |            | Only to be used for location association types LAT04 or LAT05<br/>See Notes 1-3 below on interpretation of repetitions of this composite element<br/>*Added in v1.2.0*    |
| E14D04.3.1 | Period name                             |        | 0-1      | String  |                                 |
| E14D04.3.2 | Period start date inclusive        |        | 1         | Date     |                                 |
| E14D04.3.3 | Period end date inclusive         |        | 1         | Date     |                                 |
|*E14C04.3.4*| Library closed                           |        | 0-1      |             | Explicit statement that the library location is closed on the specified days in the service period. |
|E14D04.3.4.1| Days of the week                      |        | 0-1      | String  | Days of the week are specified by a space-separated list of code values taken from LCF code list **[WKD](LCF-CodeLists.md#WKD)**. If omitted, the library location is closed on all days of the week during the specified service period. |
|*E14C04.3.5*| Library open                            |        | 0-n      |             | Explicit statement that the library location is open for at least one time period on the specified days of the service period. See Note 4 below on interpretation of repetitions of this composite element. |
|E14D04.3.5.1| Days of the week                     |        | 0-1      | String  | Days of the week are specified by a space-separated list of code values taken from LCF code list **[WKD](LCF-CodeLists.md#WKD)**. If omitted, the open time-period(s) apply to all days of the week during the specified service period. |
|*E15C04.3.5.2*| Open time-period                 |        | 1-n        |             | A single continuous period of the day during which the library location is open. It is implied that the library location is closed at times outside open time-periods. |
|E15D04.3.5.2.1| Start time                              |        | 1         | Time     |                                  |
|E15D04.3.5.2.2| End time                               |        | 1         | Time     |                                  |
|E15D04.3.5.2.3| Staffed / un-staffed                 |        | 0-1      | Code    | LCF code list **[STA](LCF-CodeLists.md#STA)**     |

**Notes on interpretation of repeated instances of E14C04.3 Library location service period**

1. If the period start/end dates of instances of E14C04.3 do not overlap, i.e. they are mutually exclusive, all are applicable.

2. If the date period of one instance of E14C04.3 is wholly contained within the date period of another instance, the instance with the wider scope is overridden by the instance with the narrow scope to the extent of the scope of the latter. An example would be to specify opening and closing times for an academic term in one instance and different times for a specific week of that term in a second instance.

3. If the date periods of two or more instances of E14C04.3 overlap, but the date period of any instance is not wholly contained within the date period of another instance, the instances cannot be interpreted unambiguously and these instances should be ignored.

4. If the days of the week of two or more instances of E14C04.3.4 and E14C04.3.5 overlap, the instances cannot be interpreted unambiguously and these instances should be ignored.

5. If the time periods of two or more instances of E14C04.3.5 overlap, the instances cannot be interpreted unambiguously and these instances should be ignored.

**Comment by franciscave** [comment] 2019-08-22 11:45
Here is a draft of the consequent changes to the LCF XML binding.

|         | *Element ID* | *XML structure*        | *Card.*  | *Data type* | *Notes* |
|------|--------------|---------------------|---------|-------------|---------|
| ...     |                        |                                    |               |                      |                |
|  13   | E14C04.3       | library-location-service-period | 0-n     |             | *Added in v1.2.0*    |
|  14   | E14D04.3.1    | period-name             | 0-1         | string      |                                    |
|  15   | E14D04.3.2   | start-date                  | 1             | date        |                                    |
|  16   | E14D04.3.3   | end-date                   | 1             | date        |                                    |
|  17   | E14C04.3.4   | closed                        | 0-1         |                 |                                    |
|  18   | E14D04.3.4.1 | days                           | 0-1        | List          | [WKD](LCF-CodeLists.md#WKD) |
|  19   | E14C04.3.5   | open                           | 0-n         |                 |                                    |
|  20   | E14D04.3.5.1 | days                           | 0-1        | List          | [WKD](LCF-CodeLists.md#WKD) |
|  21   | E14C04.3.5.2 | open-time-period     | 1-n        |                 |                                    |
|  22   | E14D04.3.5.2.1 | start-time                | 1           | time        |                                    |
|  23   | E14D04.3.5.2.2 | end-time                | 1           | time        |                                    |
|  24   | E15D04.3.5.2.3 | staffed                   | 0-1        | Code      | [STA](LCF-CodeLists.md#STA) |
| ...     |                        |                                    |               |                      |                |

In drafting this I realise that the XML binding contains inconsistencies in the 'Data type' column, with 'string' sometimes having an initial capital 'S' (which it should not). I will raise a separate issue about this. Also, we will need to add 'time' to the list of XML Schema datatypes specified in the fifth paragraph of this specification, and we will need to define the data type 'list' (a space-separated list of code values).

**Comment by franciscave** [comment] 2019-09-06 21:44
Oops! Note 5 in the above re-draft of E14 in the Data Framework is incorrect. It should be:

5.   If the time periods of two or more instances of E14C04.3.5<b><i>.2 in the same instance of E14C04.3.5</i></b> overlap, the instances cannot be interpreted unambiguously and these instances should be ignored.

Time periods in separate instances of E14C04.3.5 (open) may, of course, be the same or overlap, but must specify different days of the week. It is time periods in a single instance of E14C04.3.5

**Comment by franciscave** [comment] 2019-09-06 22:16
See pull request #194.

**Comment by franciscave** [comment] 2019-12-23 12:40
All done now.

**Closed by franciscave** 2019-12-23 12:40 UTC
Labels: Enhancement
